name: QuestDB
tabs:
- name: main_section
  label: Main
  sections:
  - name: shared_worker_count_heading
    contents:
    - type: heading
      label: Shared worker count
  - name: shared_worker_count_description
    contents:
    - type: subtitle
      label: Number of worker threads shared across the application. Increasing this number will increase parallelism in the application at the expense of CPU resources.
  - name: shared_worker_count
    contents:
    - type: number-input
      variable: config.shared_worker_count
      placeholder: "ex: 2"
      settings:
        default: 2
  - name: health_monitoring_page_heading
    contents:
    - type: heading
      label: Health monitoring
  - name: health_monitoring_page
    contents:
    - type: checkbox
      label: Enable health monitoring page
      variable: service.expose.healthcheck.enabled
      settings:
        default: true
- name: db_section
  label: Database
  sections:
  - name: root_directory_heading
    contents:
    - type: heading
      label: Root directory
  - name: root_directory_description
    contents:
    - type: subtitle
      label: Directory for storing db tables and metadata. This directory is inside the server root directory provided at startup.
  - name: root_directory
    contents:
    - type: string-input
      placeholder: "ex: db"
      variable: config.db_root
      settings:
        default: db
  - name: root_backup_directory_heading
    contents:
    - type: heading
      label: Root backup directory
  - name: root_backup_directory_description
    contents:
    - type: subtitle
      label: Output root directory for backups.
  - name: root_backup_directory
    contents:
    - type: string-input
      placeholder: "ex: backups"
      variable: config.db_backup_root
- name: advanced_section
  label: Advanced
  sections:
  - name: postgres_interface_heading
    contents:
    - type: heading
      label: Postgres Interface
  - name: postgres_interface
    contents:
    - type: variable
      variable: showPostgresSettings
      settings:
        default: true
    - type: checkbox
      label: Enable Postgres interface
      variable: service.expose.postgresql.enabled
      settings:
        default: true
  - name: postgres_settings
    contents:
    - type: string-input
      show_if: showPostgresSettings
      label: Postgres database username
      variable: config.pg_user
      placeholder: "ex: admin"
      settings:
        default: admin
    - type: string-input
      show_if: showPostgresSettings
      label: Postgres database password
      variable: config.pg_password
      placeholder: "ex: quest"
      settings:
        default: quest
  - name: telemetry_heading
    contents:
    - type: heading
      label: Telemetry
  - name: telemetry
    contents:
    - type: checkbox
      label: Enable anonymous usage metrics collection
      variable: config.enable_telemetry
      settings:
        default: true
