{{ $expose := default dict .Values.service.expose }}
{{ $influxdb := default dict $expose.influxdb }}
{{ $postgresql := default dict $expose.postgresql }}
{{ $healthcheck := default dict $expose.healthcheck }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "questdb.fullname" . }}
  labels:
    {{- include "questdb.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if $postgresql.enabled }}
    - port: {{ $postgresql.port }}
      targetPort: postgresql
      protocol: TCP
      name: postgresql
    {{ end }}
    {{- if $influxdb.enabled }}
    - port: {{ $influxdb.port }}
      targetPort: influxdb
      protocol: TCP
      name: influxdb
    {{ end }}
    {{- if $healthcheck.enabled }}
    - port: {{ $healthcheck.port }}
      targetPort: healthcheck
      protocol: TCP
      name: healthcheck
    {{ end }}
  selector:
    {{- include "questdb.selectorLabels" . | nindent 4 }}
